# Makefile for 'set' module
#
# David Kotz, April 2016, 2017, 2019, 2021
# updated by Xia Zhou, July 2016, 2018, January 2019
# edited for set by Ethan Chen, Oct. 2021
L = ../libcs50
C = ../common

OBJS = crawler.o $L/file.o $L/memory.o  $C/pagedir.o
LIBS = -lm
LLIBS = $L/libcs50-given.a

# uncomment the following to turn on verbose memory logging
